#!/bin/sh

# pupdate-install

# MIT License

# Copyright (C) 2018  Steven Stockhamer

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# used like:
# curl https://raw.githubusercontent.com/stevestock/pupdate/master/pupdate-install | bash

# In directory
RUNNING_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALL_PATH="/usr/local/bin/pupdate"
GITHUB_URL="https://github.com/stevestock/pupdate.git"

echo "================================================"
echo "🐶 pupdate Installer"
echo "================================================"
echo

git clone $GITHUB_URL --depth 1 && cd pupdate

if [ ! -d /usr/local/bin ]; then
        echo "bin not found"
    {
        echo "creating bin directory..."
        mkdir -p /usr/local/bin
    } || {
        echo "error in creating bin directory"
        exit 1
    }
fi

echo $RUNNING_DIRECTORY
cp "$RUNNING_DIRECTORY/pupdate/pupdate" $INSTALL_PATH
chmod +x $INSTALL_PATH

echo Done 🐶
echo
